# Generated by Django 3.2.25 on 2024-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240829_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediant',
            new_name='Ingredient',
        ),
    ]
