# Generated by Django 3.2.25 on 2024-08-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_ingrediant_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
